// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package webp

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/tinylib/msgp/msgp"
)

var ConfigSchema = schema.StructFunc(func(prototype *Config) *schema.StructBuilder[Config] {
	return schema.Struct(prototype,
		schema.F("default_hint", (*string)(&prototype.WebpHint), schema.String().Default("photo")),
		schema.F("default_quality", &prototype.Quality, schema.Int().Default(75)),
	).DebugName("Config")
})

func (x *Config) EncodeMsg(w *msgp.Writer) error {
	return ConfigSchema.Build().EncodeMsg(w, x)
}

var ParamsSchema = schema.StructFunc(func(prototype *Params) *schema.StructBuilder[Params] {
	return schema.Struct(prototype,
		schema.F("hint", (*string)(&prototype.WebpHint), schema.String().Default("")),
		schema.F("q", &prototype.Quality, schema.Int().Default(-1)),
	).DebugName("Params")
})

func (x *Params) EncodeMsg(w *msgp.Writer) error {
	return ParamsSchema.Build().EncodeMsg(w, x)
}
