// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package tiff

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/hsfzxjy/imbed/util/fastbuf"
)

var ConfigSchema = schema.StructFunc(func(prototype *Config) *schema.StructBuilder[Config] {
	return schema.Struct(prototype,
		schema.F("predictor", &prototype.Predictor, schema.Bool().Default(false)),
		schema.F("compression", (*string)(&prototype.Compression), schema.String().Default("deflate")),
	).DebugName("Config")
})

func (x *Config) EncodeMsg(w *fastbuf.W) {
	ConfigSchema.Build().EncodeMsg(w, x)
}

var ParamsSchema = schema.StructFunc(func(prototype *Params) *schema.StructBuilder[Params] {
	return schema.Struct(prototype,
		schema.F("pred", &prototype.Predictor, schema.Ptr(schema.Bool()).Default(nil)),
		schema.F("c", (*string)(&prototype.Compression), schema.String().Default("")),
	).DebugName("Params")
})

func (x *Params) EncodeMsg(w *fastbuf.W) {
	ParamsSchema.Build().EncodeMsg(w, x)
}
