// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/hsfzxjy/imbed/util/fastbuf"
)

var brightnessSchema = schema.StructFunc(func(prototype *brightness) *schema.StructBuilder[brightness] {
	return schema.Struct(prototype,
		schema.F("p", &prototype.Percentage, schema.Rat()),
	).DebugName("brightness")
})

func (x *brightness) EncodeMsg(w *fastbuf.W) {
	brightnessSchema.Build().EncodeMsg(w, x)
}
