// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/tinylib/msgp/msgp"
)

var brightnessApplierSchema = schema.StructFunc(func(prototype *brightnessApplier) *schema.StructBuilder[brightnessApplier] {
	return schema.Struct(prototype,
		schema.F("percentage", &prototype.percentage, schema.Rat()),
	).DebugName("brightnessApplier")
})

func (x *brightnessApplier) EncodeMsg(w *msgp.Writer) error {
	return brightnessApplierSchema.Build().EncodeMsg(w, x)
}

var brightnessParamsSchema = schema.StructFunc(func(prototype *brightnessParams) *schema.StructBuilder[brightnessParams] {
	return schema.Struct(prototype,
		schema.F("p", &prototype.Percentage, schema.Rat()),
	).DebugName("brightnessParams")
})

func (x *brightnessParams) EncodeMsg(w *msgp.Writer) error {
	return brightnessParamsSchema.Build().EncodeMsg(w, x)
}
