// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/tinylib/msgp/msgp"
)

var brightnessSchema = schema.StructFunc(func(prototype *brightness) *schema.StructBuilder[brightness] {
	return schema.Struct(prototype,
		schema.F("p", &prototype.Percentage, schema.Rat()),
	).DebugName("brightness")
})

func (x *brightness) EncodeMsg(w *msgp.Writer) error {
	return brightnessSchema.Build().EncodeMsg(w, x)
}
