// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/hsfzxjy/imbed/util/fastbuf"
)

var colorizeSchema = schema.StructFunc(func(prototype *colorize) *schema.StructBuilder[colorize] {
	return schema.Struct(prototype,
		schema.F("h", &prototype.H, schema.Rat()),
		schema.F("s", &prototype.S, schema.Rat()),
		schema.F("p", &prototype.P, schema.Rat()),
	).DebugName("colorize")
})

func (x *colorize) EncodeMsg(w *fastbuf.W) {
	colorizeSchema.Build().EncodeMsg(w, x)
}
