// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/hsfzxjy/imbed/util/rats"
	"github.com/tinylib/msgp/msgp"
)

var colorBalanceSchema = schema.StructFunc(func(prototype *colorBalance) *schema.StructBuilder[colorBalance] {
	return schema.Struct(prototype,
		schema.F("r", &prototype.r, schema.Rat().Default(rats.R0)),
		schema.F("g", &prototype.g, schema.Rat().Default(rats.R0)),
		schema.F("b", &prototype.b, schema.Rat().Default(rats.R0)),
	).DebugName("colorBalance")
})

func (x *colorBalance) EncodeMsg(w *msgp.Writer) error {
	return colorBalanceSchema.Build().EncodeMsg(w, x)
}
