// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/hsfzxjy/imbed/util/fastbuf"
)

var contrastSchema = schema.StructFunc(func(prototype *contrast) *schema.StructBuilder[contrast] {
	return schema.Struct(prototype,
		schema.F("p", &prototype.Percentage, schema.Rat()),
	).DebugName("contrast")
})

func (x *contrast) EncodeMsg(w *fastbuf.W) {
	contrastSchema.Build().EncodeMsg(w, x)
}
