// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/tinylib/msgp/msgp"
)

var grayScaleSchema = schema.StructFunc(func(prototype *grayScale) *schema.StructBuilder[grayScale] {
	return schema.Struct(prototype).DebugName("grayScale")
})

func (x *grayScale) EncodeMsg(w *msgp.Writer) error {
	return grayScaleSchema.Build().EncodeMsg(w, x)
}
