// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/hsfzxjy/imbed/util/fastbuf"
)

var grayScaleSchema = schema.StructFunc(func(prototype *grayScale) *schema.StructBuilder[grayScale] {
	return schema.Struct(prototype).DebugName("grayScale")
})

func (x *grayScale) EncodeMsg(w *fastbuf.W) {
	grayScaleSchema.Build().EncodeMsg(w, x)
}
