// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/hsfzxjy/imbed/util/fastbuf"
)

var hueSchema = schema.StructFunc(func(prototype *hue) *schema.StructBuilder[hue] {
	return schema.Struct(prototype,
		schema.F("x", &prototype.X, schema.Rat()),
	).DebugName("hue")
})

func (x *hue) EncodeMsg(w *fastbuf.W) {
	hueSchema.Build().EncodeMsg(w, x)
}
