// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/tinylib/msgp/msgp"
)

var invertSchema = schema.StructFunc(func(prototype *invert) *schema.StructBuilder[invert] {
	return schema.Struct(prototype).DebugName("invert")
})

func (x *invert) EncodeMsg(w *msgp.Writer) error {
	return invertSchema.Build().EncodeMsg(w, x)
}
