// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/hsfzxjy/imbed/util/fastbuf"
)

var opacitySchema = schema.StructFunc(func(prototype *opacity) *schema.StructBuilder[opacity] {
	return schema.Struct(prototype,
		schema.F("p", &prototype.Percentage, schema.Rat()),
	).DebugName("opacity")
})

func (x *opacity) EncodeMsg(w *fastbuf.W) {
	opacitySchema.Build().EncodeMsg(w, x)
}
