// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/tinylib/msgp/msgp"
)

var opacityApplierSchema = schema.StructFunc(func(prototype *opacityApplier) *schema.StructBuilder[opacityApplier] {
	return schema.Struct(prototype,
		schema.F("alphaBit", &prototype.alphaBit, schema.Int()),
	).DebugName("opacityApplier")
})

func (x *opacityApplier) EncodeMsg(w *msgp.Writer) error {
	return opacityApplierSchema.Build().EncodeMsg(w, x)
}

var opacityParamsSchema = schema.StructFunc(func(prototype *opacityParams) *schema.StructBuilder[opacityParams] {
	return schema.Struct(prototype,
		schema.F("v", &prototype.Value, schema.Rat()),
	).DebugName("opacityParams")
})

func (x *opacityParams) EncodeMsg(w *msgp.Writer) error {
	return opacityParamsSchema.Build().EncodeMsg(w, x)
}
