// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/hsfzxjy/imbed/util/fastbuf"
)

var pixelateSchema = schema.StructFunc(func(prototype *pixelate) *schema.StructBuilder[pixelate] {
	return schema.Struct(prototype,
		schema.F("size", &prototype.Size, schema.Int()),
	).DebugName("pixelate")
})

func (x *pixelate) EncodeMsg(w *fastbuf.W) {
	pixelateSchema.Build().EncodeMsg(w, x)
}
