// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/tinylib/msgp/msgp"
)

var resizeApplierSchema = schema.StructFunc(func(prototype *resizeApplier) *schema.StructBuilder[resizeApplier] {
	return schema.Struct(prototype,
		schema.F("resizeParams", &prototype.resizeParams, resizeParamsSchema),
	).DebugName("resizeApplier")
})

func (x *resizeApplier) EncodeMsg(w *msgp.Writer) error {
	return resizeApplierSchema.Build().EncodeMsg(w, x)
}

var resizeConfigSchema = schema.StructFunc(func(prototype *resizeConfig) *schema.StructBuilder[resizeConfig] {
	return schema.Struct(prototype).DebugName("resizeConfig")
})

func (x *resizeConfig) EncodeMsg(w *msgp.Writer) error {
	return resizeConfigSchema.Build().EncodeMsg(w, x)
}

var resizeParamsSchema = schema.StructFunc(func(prototype *resizeParams) *schema.StructBuilder[resizeParams] {
	return schema.Struct(prototype,
		schema.F("h", &prototype.H, schema.Int().Default(0)),
		schema.F("w", &prototype.W, schema.Int().Default(0)),
		schema.F("sample", &prototype.Resampling, schema.String().Default("cub")),
		schema.F("anchor", &prototype.Anchor, schema.String().Default("c")),
		schema.F("mode", &prototype.Mode, schema.String().Default("default")),
	).DebugName("resizeParams")
})

func (x *resizeParams) EncodeMsg(w *msgp.Writer) error {
	return resizeParamsSchema.Build().EncodeMsg(w, x)
}
