// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/hsfzxjy/imbed/util/fastbuf"
)

var resizeSchema = schema.StructFunc(func(prototype *resize) *schema.StructBuilder[resize] {
	return schema.Struct(prototype,
		schema.F("h", &prototype.H, schema.Int().Default(0)),
		schema.F("w", &prototype.W, schema.Int().Default(0)),
		schema.F("sample", (*string)(&prototype.Resampling), schema.String().Default("cub")),
		schema.F("anchor", (*string)(&prototype.Anchor), schema.String().Default("c")),
		schema.F("mode", &prototype.Mode, schema.String().Default("default")),
	).DebugName("resize")
})

func (x *resize) EncodeMsg(w *fastbuf.W) {
	resizeSchema.Build().EncodeMsg(w, x)
}
