// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/tinylib/msgp/msgp"
)

var saturationSchema = schema.StructFunc(func(prototype *saturation) *schema.StructBuilder[saturation] {
	return schema.Struct(prototype,
		schema.F("p", &prototype.p, schema.Rat()),
	).DebugName("saturation")
})

func (x *saturation) EncodeMsg(w *msgp.Writer) error {
	return saturationSchema.Build().EncodeMsg(w, x)
}
