// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/tinylib/msgp/msgp"
)

var sepiaSchema = schema.StructFunc(func(prototype *sepia) *schema.StructBuilder[sepia] {
	return schema.Struct(prototype,
		schema.F("p", &prototype.p, schema.Rat()),
	).DebugName("sepia")
})

func (x *sepia) EncodeMsg(w *msgp.Writer) error {
	return sepiaSchema.Build().EncodeMsg(w, x)
}
