// Code generated by "github.com/hsfzxjy/imbed/schema/gen"; DO NOT EDIT.

package gift

import (
	"github.com/hsfzxjy/imbed/schema"
	"github.com/hsfzxjy/imbed/util/rats"
	"github.com/tinylib/msgp/msgp"
)

var sigmoidSchema = schema.StructFunc(func(prototype *sigmoid) *schema.StructBuilder[sigmoid] {
	return schema.Struct(prototype,
		schema.F("factor", &prototype.Factor, schema.Rat()),
		schema.F("mid", &prototype.Midpoint, schema.Rat().Default(rats.R1_2)),
	).DebugName("sigmoid")
})

func (x *sigmoid) EncodeMsg(w *msgp.Writer) error {
	return sigmoidSchema.Build().EncodeMsg(w, x)
}
